name: Publish Extension
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g @vscode/vsce
      - run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
